language: r

sudo: required

before_install:
  - sudo apt-get install libv8-dev

r_binary_packages:
  - rgbif sp rworldmap maps covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
